Algoritmo "escola_ribeirao"
// Professor   : Cintia Pinho
// Descrição   : Faça um programa que peça ao usuário para digitar a melhor escola de Ribeirão Pires.
// Autor(a)    : Vinicius Silva Augusto
// Data atual  : 20/09/2022
Var
esc: caractere

Inicio
repita
escreval ("Qual é a melhor escola de Ribeirão Pires?")
leia(esc)
ate((esc="Etec MCM") ou (esc="ETEC MCM") ou (esc="etec mcm"))

Fimalgoritmo