Algoritmo "media3numeros"
// Descrição   : fazer a media de tres numeros
// Autor(a)    : Vinicius Silva Augusto
// Data atual  : 08/03/2022
Var
n1,n2,n3,media:real


Inicio
//entrada
escreval("digite o primeiro numero:",n1)
leia(n1)
escreval("digite o segundo numero:",n2)
leia(n2)
escreval("digite o terceiro numero:",n3)
leia(n3)
//processamento
media<-(n1+n2+n3)/3
//saida
escreval("a media dos tres numeros é:",media)


Fimalgoritmo