algoritmo " QUANTPEÇAS"
// Função : Solicita o valor da peça e quantidade cpmprada e infomrar o valor da compra
// Autor : Cinitia Pinho
// Data : 26/04/2022
// Seção de Declarações 
var
valor,qtde,total:real
inicio
//entrada
escreval("digite  a quantidade de pecas compradas")
leia(qtde)
escreval("digite o valor unitario de cada peca")
leia(valor)
//processamento
total<-valor*qtde
//saida
escreval("o valor total da sua compra é: ",total)
// Seção de Comandos 
fimalgoritmo
